run:
	python manage.py runserver 8080

test:
	python manage.py test

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

resetdb:
	python manage.py flush
	python manage.py createclasses
	python manage.py createtestusers

shell:
	python manage.py shell

