# Generated by Django 2.0.5 on 2018-06-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_groups.ClassGroup'),
        ),
    ]
