# Generated by Django 2.0.5 on 2018-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0002_auto_20180604_1743'),
        ('sis_users', '0002_auto_20180604_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='classes',
            field=models.ManyToManyField(to='class_groups.ClassGroup'),
        ),
    ]
