# Generated by Django 2.0.5 on 2018-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0002_auto_20180601_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(default='', max_length=254)),
                ('staff', models.BooleanField(default=False)),
            ],
        ),
    ]
