# Generated by Django 2.0.5 on 2018-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0003_userstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.CharField(choices=[('T1', 'Technical - Set 1'), ('T2', 'Technical - Set 2'), ('T3', 'Technical - Set 3'), ('V1', 'Vocational - Set 1'), ('V2', 'Vocational - Set 2'), ('V3', 'Vocational - Set 3')], default='T1', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year_group',
            field=models.IntegerField(choices=[(10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], default=10),
            preserve_default=False,
        ),
    ]
