# Generated by Django 2.0.5 on 2018-06-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0005_auto_20180601_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
