# Generated by Django 2.0.5 on 2018-06-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0005_auto_20180610_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_group',
            new_name='set',
        ),
        migrations.AlterField(
            model_name='userstate',
            name='set',
            field=models.IntegerField(choices=[(1, 'Set 1'), (2, 'Set 2'), (3, 'Set 3')], null=True),
        ),
    ]
