# Generated by Django 2.0.5 on 2018-06-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0006_userstate_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_group',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_groups.ClassGroup'),
        ),
    ]
