# Generated by Django 2.0.5 on 2018-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0007_auto_20180602_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='year_group',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='class_group',
        ),
        migrations.AddField(
            model_name='userstate',
            name='band',
            field=models.CharField(choices=[('T', 'Technical'), ('V', 'Vocational')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='set',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], null=True),
        ),
    ]
