# Generated by Django 2.0.5 on 2018-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0009_auto_20180604_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstate',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
