# Generated by Django 2.0.5 on 2018-06-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0011_auto_20180604_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_group',
        ),
    ]
