# Generated by Django 2.0.5 on 2018-06-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0006_auto_20180602_1149'),
        ('sis_users', '0012_remove_student_class_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_groups.ClassGroup'),
        ),
    ]
