# Generated by Django 2.0.5 on 2018-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_group', models.IntegerField(choices=[(10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('class_name', models.TextField(choices=[('T1', 'Technical - Set 1'), ('T2', 'Technical - Set 2'), ('T3', 'Technical - Set 3'), ('V1', 'Vocational - Set 1'), ('V2', 'Vocational - Set 2'), ('V3', 'Vocational - Set 3')], max_length=2)),
            ],
        ),
    ]
