# Generated by Django 2.0.5 on 2018-06-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0007_auto_20180602_0831'),
        ('class_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(to='sis_users.Staff'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='class_name',
            field=models.CharField(choices=[('T1', 'Technical - Set 1'), ('T2', 'Technical - Set 2'), ('T3', 'Technical - Set 3'), ('V1', 'Vocational - Set 1'), ('V2', 'Vocational - Set 2'), ('V3', 'Vocational - Set 3')], max_length=2),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subjects',
            field=models.ManyToManyField(to='class_groups.Subject'),
        ),
    ]
