# Generated by Django 2.0.5 on 2018-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_groups', '0001_initial'),
        ('sis_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='sis_users.Staff'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='subjects',
            field=models.ManyToManyField(to='class_groups.Subject'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(to='sis_users.Staff'),
        ),
    ]
