# Generated by Django 2.0.5 on 2018-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_users', '0007_auto_20180602_0831'),
        ('class_groups', '0002_auto_20180602_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(to='sis_users.Staff'),
        ),
    ]
