# Generated by Django 2.0.5 on 2018-06-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0003_auto_20180610_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='set',
            name='value',
            field=models.IntegerField(choices=[(1, 'Set 1'), (2, 'Set 2'), (3, 'Set 3')]),
        ),
        migrations.DeleteModel(
            name='ClassGroup',
        ),
    ]
