# Generated by Django 2.0.5 on 2018-06-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0003_subject_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='class_name',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='band',
            field=models.CharField(choices=[('T', 'Technical'), ('V', 'Vocational')], default='T', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classgroup',
            name='set',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
            preserve_default=False,
        ),
    ]
