# Generated by Django 2.0.5 on 2018-06-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0004_auto_20180602_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classgroup',
            old_name='year_group',
            new_name='year',
        ),
    ]
