# Generated by Django 2.0.5 on 2018-06-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_groups', '0005_auto_20180602_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='name',
        ),
    ]
